### ISSUE TITLE
ModuleNotFoundError: No module named 'AppKit'

### ISSUE THREAD

**Issue by chriszanf** [drewdiver/ncprefs.py#1]
Running macOS Catalina 10.15
Testing this as could use it going forwards and met with this error message when I first ran it.

```
python3 /usr/local/bin/ncprefs.py
Traceback (most recent call last):
  File "/usr/local/bin/ncprefs.py", line 8, in <module>
    from AppKit import NSWorkspace
```

Resolved by running `pip3 install pyobjc`

**Comment by drewdiver** [comment]
I should update the read me listing PyObj-C as a requirement

**Comment by drewdiver** [comment]
Updated README.md with PyObjC requirement
